<%@ Page Title="" Language="C#" MasterPageFile="~/Main.Master" AutoEventWireup="true" CodeBehind="ChinhSachDoiHoan.aspx.cs" Inherits="QLBHVanPhongPham.ChinhSachDoiHoan" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
    .auto-style28 {
        color: #000000;
    }
    .auto-style29 {
        font-size: medium;
        color: #000000;
    }
        .auto-style30 {
            text-align: center;
            color: #000000;
            font-size: medium;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <p class="auto-style30">
    <strong>CHÍNH SÁCH ĐỔI TRẢ &amp; HOÀN TIỀN</strong></p>
<p class="auto-style9" style="box-sizing: border-box; margin: 0px 0px 15px; color: rgb(37, 37, 37); font-family: &quot;Product Sans&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <span style="box-sizing: border-box; font-size: 20px;"><span style="box-sizing: border-box; background: white;"><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;, serif;"><strong style="box-sizing: border-box; font-weight: 700;"><span style="box-sizing: border-box; font-family: Calibri, sans-serif;"><span style="box-sizing: border-box; color: red;">Quy định về đổi trả</span></span></strong></span></span></span></p>
<p class="auto-style9" style="box-sizing: border-box; margin: 0px 0px 15px; color: rgb(37, 37, 37); font-family: &quot;Product Sans&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <span style="box-sizing: border-box; font-size: 20px;"><span style="box-sizing: border-box; background: white;"><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;, serif;"><span style="box-sizing: border-box; font-family: Calibri, sans-serif;"><span style="box-sizing: border-box; color: black;">- Hàng hóa được chấp nhận đổi/trả trong vòng<a style="box-sizing: border-box; background: transparent; color: rgb(37, 37, 37); text-decoration: none;"><strong style="box-sizing: border-box; font-weight: 700;">7 ngày làm việc</strong></a></span>&nbsp;<span style="box-sizing: border-box; color: black;">tính từ ngày Quý Khách nhận được hàng.</span></span></span></span></span></p>
<p class="auto-style9" style="box-sizing: border-box; margin: 0px 0px 15px; color: rgb(37, 37, 37); font-family: &quot;Product Sans&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <span style="box-sizing: border-box; font-size: 20px;"><span style="box-sizing: border-box; background: white;"><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;, serif;"><span style="box-sizing: border-box; font-family: Calibri, sans-serif;"><span style="box-sizing: border-box; color: black;">- Hàng được đổi ngang giá hoặc giá trị cao hơn giá trị hàng đổi thì khách hàng bù phần chênh lệch</span></span></span></span></span></p>
<p class="auto-style9" style="box-sizing: border-box; margin: 0px 0px 15px; color: rgb(37, 37, 37); font-family: &quot;Product Sans&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <span style="box-sizing: border-box; font-size: 20px;"><span style="box-sizing: border-box; background: white;"><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;, serif;"><span style="box-sizing: border-box; font-family: Calibri, sans-serif;"><span style="box-sizing: border-box; color: black;">- Chỉ hoàn tiền khi lỗi nhà sản xuất và không có sản phẩm khác thay thế</span></span></span></span></span></p>
<p class="auto-style9" style="box-sizing: border-box; margin: 0px 0px 15px; color: rgb(37, 37, 37); font-family: &quot;Product Sans&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <span style="box-sizing: border-box; font-size: 20px;"><span style="box-sizing: border-box; background: white;"><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;, serif;"><strong style="box-sizing: border-box; font-weight: 700;"><span style="box-sizing: border-box; font-family: Calibri, sans-serif;"><span style="box-sizing: border-box; color: black;">1.1&nbsp; Trường hợp áp dụng đổi trả</span></span></strong></span></span></span></p>
<p class="auto-style9" style="box-sizing: border-box; margin: 0px 0px 15px; color: rgb(37, 37, 37); font-family: &quot;Product Sans&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <span style="box-sizing: border-box; font-size: 20px;"><span style="box-sizing: border-box; background: white;"><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;, serif;"><span style="box-sizing: border-box; font-family: Calibri, sans-serif;"><span style="box-sizing: border-box; color: black;">- Hàng không đúng chủng loại, mẫu mã như trên website.<br style="box-sizing: border-box;" />
    - Không đủ số lượng, quy cách đóng gói, mô tả như trên website<br style="box-sizing: border-box;" />
    - Hàng hóa bị hư hỏng, bể vỡ, bong tróc….<br style="box-sizing: border-box;" />
    - Sản phẩm hết hạn sử dụng.&nbsp;</span></span></span></span></span></p>
<p class="auto-style9" style="box-sizing: border-box; margin: 0px 0px 15px; color: rgb(37, 37, 37); font-family: &quot;Product Sans&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <span style="box-sizing: border-box; font-size: 20px;"><span style="box-sizing: border-box; background: white;"><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;, serif;"><strong style="box-sizing: border-box; font-weight: 700;"><span style="box-sizing: border-box; font-family: Calibri, sans-serif;"><span style="box-sizing: border-box; color: black;">1.2&nbsp; Điều kiện đổi trả</span></span></strong></span></span></span></p>
<p class="auto-style9" style="box-sizing: border-box; margin: 0px 0px 15px; color: rgb(37, 37, 37); font-family: &quot;Product Sans&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <span style="box-sizing: border-box; font-size: 20px;"><span style="box-sizing: border-box; background: white;"><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;, serif;"><span style="box-sizing: border-box; font-family: Calibri, sans-serif;"><span style="box-sizing: border-box; color: black;">- Sản phẩm còn nguyên vẹn, đầy đủ bao bì, hộp, tài liệu hướng dẫn sử dụng linh kiện, phụ kiện, quà tặng (nếu có).<br style="box-sizing: border-box;" />
    - Đầy đủ hóa đơn, tem trên sản phẩm, phiếu bảo hành (nếu có).<br style="box-sizing: border-box;" />
    - Tình trạng sản phẩm không bị trầy xướt, nứt vỡ, ẩm ướt, dính hóa chất, can thiệp sửa chữa .<br style="box-sizing: border-box;" />
    - Sản phẩm chưa qua sử dụng (trừ trường hợp đổi trả do lỗi kỹ thuật).<br style="box-sizing: border-box;" />
    - Chúng tôi có quyền từ chối việc đổi trả trong trường hợp phát hiện sản phẩm đã bị sử dụng hoặc hư hỏng, bể vỡ do Quý Khách hàng.&nbsp;</span></span></span></span></span></p>
<p class="auto-style9" style="box-sizing: border-box; margin: 0px 0px 15px; color: rgb(37, 37, 37); font-family: &quot;Product Sans&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <span style="box-sizing: border-box; font-size: 20px;"><span style="box-sizing: border-box; background: white;"><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;, serif;"><strong style="box-sizing: border-box; font-weight: 700;"><i style="box-sizing: border-box;"><span style="box-sizing: border-box; font-family: Calibri, sans-serif;"><span style="box-sizing: border-box; color: red;">Lưu ý:</span></span></i></strong><em style="box-sizing: border-box; font-style: italic;"><span style="box-sizing: border-box; font-family: Calibri, sans-serif;"><span style="box-sizing: border-box; color: black;">&nbsp;Đối với sản phẩm thiết bị điện tử, tin học áp dụng theo chính sách đổi trả của nhà sản xuất.</span></span></em>&nbsp;</span></span></span></p>
<p class="auto-style9" style="box-sizing: border-box; margin: 0px 0px 15px; color: rgb(37, 37, 37); font-family: &quot;Product Sans&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <span style="box-sizing: border-box; font-size: 20px;"><span style="box-sizing: border-box; background: white;"><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;, serif;"><strong style="box-sizing: border-box; font-weight: 700;"><span style="box-sizing: border-box; font-family: Calibri, sans-serif;"><span style="box-sizing: border-box; color: black;">1.3&nbsp; Hình thức đổi trả</span></span></strong><br style="box-sizing: border-box;" />
    <span style="box-sizing: border-box; font-family: Calibri, sans-serif;"><span style="box-sizing: border-box; color: black;">Quý Khách vận chuyển hàng hóa kèm theo hóa đơn/chứng từ đến địa chỉ</span></span>&nbsp;<span style="box-sizing: border-box; font-family: Calibri, sans-serif;"><span style="box-sizing: border-box; color: black;">tiếp nhận hàng đổi trả hàng tại khu vực&nbsp;<strong style="box-sizing: border-box; font-weight: 700;">Hồ Chí Minh: 336A23 Phan Văn Trị, Phường 5, Q. Gò Vấp</strong></span></span></span></span></span></p>
<p class="auto-style9" style="box-sizing: border-box; margin: 0px 0px 15px; color: rgb(37, 37, 37); font-family: &quot;Product Sans&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <span style="box-sizing: border-box; font-size: 20px;"><span style="box-sizing: border-box; background: white;"><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;, serif;"><span style="box-sizing: border-box; font-family: Calibri, sans-serif;"><span style="box-sizing: border-box; color: black;">Trong trường hợp Quý khách không thể tự vận chuyển hàng đổi trả đến địa chỉ tiếp nhận như trên, vui lòng liên hệ với chúng tôi qua số Hotline 0896918585 để được hỗ trợ tư vấn</span></span></span></span></span></p>
<p>
    &nbsp;</p>
</asp:Content>
