<%@ Page Title="" Language="C#" MasterPageFile="~/Main.Master" AutoEventWireup="true" CodeBehind="ChinhSachGiaoHang.aspx.cs" Inherits="QLBHVanPhongPham.ChinhSachGiaoHang" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
    .auto-style28 {
        color: #000000;
    }
    .auto-style30 {
        text-align: left;
        color: rgb(0, 0, 0);
        font-family: Calibri, sans-serif;
        font-size: 20px;
        font-style: normal;
        font-weight: bold;
        letter-spacing: normal;
        text-indent: 0px;
        text-transform: none;
        word-spacing: 0px;
        white-space: normal;
        margin-left: 0px;
        margin-right: 0px;
        margin-top: 0px;
        margin-bottom: 15px;
        background-color: rgb(255, 255, 255);
    }
    .auto-style31 {
        text-align: left;
        height: 55px;
    }
    .auto-style32 {
        font-weight: normal;
    }
    .auto-style33 {
        font-size: medium;
        color: #000000;
    }
</style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <p class="auto-style33">
    <strong>CHÍNH SÁCH GIAO HÀNG</strong></p>
<div>
    <p class="auto-style9" style="box-sizing: border-box; margin: 0px 0px 15px; color: rgb(37, 37, 37); font-family: &quot;Product Sans&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <span style="box-sizing: border-box; font-size: 20px;"><span style="box-sizing: border-box; background: white;"><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;, serif;"><strong style="box-sizing: border-box; font-weight: 700;"><span style="box-sizing: border-box; font-family: Calibri, sans-serif;"><span style="box-sizing: border-box; color: black;">Phạm vi giao hàng</span></span></strong></span></span></span></p>
    <p class="auto-style9" style="box-sizing: border-box; margin: 0px 0px 15px; color: rgb(37, 37, 37); font-family: &quot;Product Sans&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <span style="box-sizing: border-box; font-size: 20px;"><span style="box-sizing: border-box; background: white;"><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;, serif;"><span style="box-sizing: border-box; font-family: Calibri, sans-serif;"><span style="box-sizing: border-box; color: black;">Chúng tôi luôn hỗ trợ giao hàng tại tất cả các tỉnh thành trên Toàn Quốc</span></span></span></span></span></p>
    <p class="auto-style9" style="box-sizing: border-box; margin: 0px 0px 15px; color: rgb(37, 37, 37); font-family: &quot;Product Sans&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <span style="box-sizing: border-box; font-size: 20px;"><span style="box-sizing: border-box; background: white;"><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;, serif;"><strong style="box-sizing: border-box; font-weight: 700;"><span style="box-sizing: border-box; font-family: Calibri, sans-serif;"><span style="box-sizing: border-box; color: black;">Thời gian giao hàng</span></span></strong></span></span></span></p>
    <p class="auto-style9" style="box-sizing: border-box; margin: 0px 0px 15px; color: rgb(37, 37, 37); font-family: &quot;Product Sans&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <span style="box-sizing: border-box; font-size: 20px;"><span style="box-sizing: border-box; background: white;"><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;, serif;"><span style="box-sizing: border-box; font-family: Calibri, sans-serif;"><span style="box-sizing: border-box; color: black;">Thời gian giao hàng từ&nbsp;<strong style="box-sizing: border-box; font-weight: 700;">2-3 ngày</strong>&nbsp;làm việc (từ&nbsp;<strong style="box-sizing: border-box; font-weight: 700;">08h</strong>&nbsp;đến&nbsp;<strong style="box-sizing: border-box; font-weight: 700;">17h30</strong>&nbsp;từ&nbsp;<strong style="box-sizing: border-box; font-weight: 700;">thứ Hai</strong>&nbsp;đến&nbsp;<strong style="box-sizing: border-box; font-weight: 700;">thứ Bảy</strong>) đối với các đơn hàng trong nội tỉnh Hồ Chí Minh.</span></span></span></span></span></p>
    <p class="auto-style9" style="box-sizing: border-box; margin: 0px 0px 15px; color: rgb(37, 37, 37); font-family: &quot;Product Sans&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <span style="box-sizing: border-box; font-size: 20px;"><span style="box-sizing: border-box; background: white;"><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;, serif;"><span style="box-sizing: border-box; font-family: Calibri, sans-serif;"><span style="box-sizing: border-box; color: black;">Các đơn hàng liên tỉnh được giao hàng từ&nbsp;<strong style="box-sizing: border-box; font-weight: 700;">4-6 ngày</strong>&nbsp;làm việc (từ<strong style="box-sizing: border-box; font-weight: 700;">&nbsp;08h&nbsp;</strong>đến<strong style="box-sizing: border-box; font-weight: 700;">&nbsp;17h30&nbsp;</strong>từ<strong style="box-sizing: border-box; font-weight: 700;">&nbsp;thứ Hai&nbsp;</strong>đến<strong style="box-sizing: border-box; font-weight: 700;">&nbsp;thứ Bảy</strong>) cho các huyện/ thành phố trung tâm, các đơn giao xuống huyện/xã sẽ cộng thêm 1 ngày làm việc.&nbsp;</span></span></span></span></span></p>
    <p class="auto-style9" style="box-sizing: border-box; margin: 0px 0px 15px; color: rgb(37, 37, 37); font-family: &quot;Product Sans&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <span style="box-sizing: border-box; font-size: 20px;"><span style="box-sizing: border-box; background: white;"><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;, serif;"><span style="box-sizing: border-box; font-family: Calibri, sans-serif;"><span style="box-sizing: border-box; color: black;">Thời gian giao hàng được bắt đầu tính sau khi đơn hàng của quý khách được xác nhận thành công bằng cuộc gọi của nhân viên chăm sóc khách hàng của chúng tôi.&nbsp;</span></span></span></span></span></p>
    <p class="auto-style9" style="box-sizing: border-box; margin: 0px 0px 15px; color: rgb(37, 37, 37); font-family: &quot;Product Sans&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <span style="box-sizing: border-box; font-size: 20px;"><span style="box-sizing: border-box; background: white;"><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;, serif;"><strong style="box-sizing: border-box; font-weight: 700;"><span style="box-sizing: border-box; font-family: Calibri, sans-serif;"><span style="box-sizing: border-box; color: black;">Phí giao hàng</span></span></strong></span></span></span></p>
    <p class="auto-style9" style="box-sizing: border-box; margin: 0px 0px 15px; color: rgb(37, 37, 37); font-family: &quot;Product Sans&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <span style="box-sizing: border-box; font-size: 20px;"><span style="box-sizing: border-box; background: white;"><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;, serif;"><span style="box-sizing: border-box; font-family: Calibri, sans-serif;"><span style="box-sizing: border-box; color: black;">Đơn hàng đặt trực tuyến có giá trị thanh toán<strong style="box-sizing: border-box; font-weight: 700;">&nbsp;&gt;= 300.000</strong></span>&nbsp;</span><strong style="box-sizing: border-box; font-weight: 700;"><span style="box-sizing: border-box; font-family: Calibri, sans-serif;"><span style="box-sizing: border-box; color: black;">VNĐ</span></span></strong><span style="box-sizing: border-box; font-family: Calibri, sans-serif;"><span style="box-sizing: border-box; color: black;">&nbsp;(sau khuyến mãi) sẽ được<span>&nbsp;</span></span><span style="box-sizing: border-box; color: rgb(231, 76, 60);"><strong style="box-sizing: border-box; font-weight: 700;">miễn phí giao hàng</strong></span><span style="box-sizing: border-box; color: black;">.</span></span></span></span></span></p>
    <p class="auto-style9" style="box-sizing: border-box; margin: 0px 0px 15px; color: rgb(37, 37, 37); font-family: &quot;Product Sans&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <font color="#000000" face="Calibri, sans-serif" style="box-sizing: border-box;"><span style="box-sizing: border-box; font-size: 20px;">Đơn hàng đặt trực tuyến có giá trị thanh toán &lt; 300.000 VNĐ sẽ phát sinh chi phí vận chuyển thực tế tùy thuộc vào địa điểm khách nhận hàng.</span></font></p>
    <p class="auto-style9" style="box-sizing: border-box; margin: 0px 0px 15px; color: rgb(37, 37, 37); font-family: &quot;Product Sans&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <span style="box-sizing: border-box; font-size: 20px;"><span style="box-sizing: border-box; background: white;"><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;, serif;"><span style="box-sizing: border-box; font-family: Calibri, sans-serif;"><span style="box-sizing: border-box; color: black;">Mỗi đơn hàng chỉ giao đến 01 địa chỉ của Quý khách.</span></span></span></span></span></p>
    <p class="auto-style9" style="box-sizing: border-box; margin: 0px 0px 15px; color: rgb(37, 37, 37); font-family: &quot;Product Sans&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <span style="box-sizing: border-box; font-size: 20px;"><span style="box-sizing: border-box; background: white;"><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;, serif;"><strong style="box-sizing: border-box; font-weight: 700;"><span style="box-sizing: border-box; font-family: Calibri, sans-serif;"><span style="box-sizing: border-box; color: black;">Theo dõi đơn hàng</span></span></strong></span></span></span></p>
    <p class="auto-style9" style="box-sizing: border-box; margin: 0px 0px 15px; color: rgb(37, 37, 37); font-family: &quot;Product Sans&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <span style="box-sizing: border-box; font-size: 20px;"><span style="box-sizing: border-box; background: white;"><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;, serif;"><span style="box-sizing: border-box; font-family: Calibri, sans-serif;"><span style="box-sizing: border-box; color: black;">Các trạng thái xử lý đơn hàng của&nbsp;<b style="box-sizing: border-box; font-weight: 700;">Cleverbox</b>&nbsp;sẽ được gửi đến email mà quý khách đã cung cấp khi mua hàng.</span></span></span></span></span></p>
    <p class="auto-style9" style="box-sizing: border-box; margin: 0px 0px 15px; color: rgb(37, 37, 37); font-family: &quot;Product Sans&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <span style="box-sizing: border-box; font-size: 20px;"><span style="box-sizing: border-box; background: white;"><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;, serif;"><span style="box-sizing: border-box; font-family: Calibri, sans-serif;"><span style="box-sizing: border-box; color: black;">Vì thế quý khách có thể kiểm tra email để xem đơn hàng của mình đã được xuất kho và giao cho nhà vận chuyển hay chưa</span></span></span></span></span></p>
    <p class="auto-style9" style="box-sizing: border-box; margin: 0px 0px 15px; color: rgb(37, 37, 37); font-family: &quot;Product Sans&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <br style="box-sizing: border-box;" />
        <span style="box-sizing: border-box; font-size: 20px;"><span style="box-sizing: border-box; background: white;"><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;, serif;"><strong style="box-sizing: border-box; font-weight: 700;"><span style="box-sizing: border-box; font-family: Calibri, sans-serif;"><span style="box-sizing: border-box; color: black;">Kiểm tra nhận hàng</span></span></strong></span></span></span></p>
    <p class="auto-style30" style="box-sizing: border-box; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="auto-style32">Hiện tại, </span>Cleverbox không <span class="auto-style32">cung cấp dịch vụ</span> đồng kiểm hàng (hay kiểm tra hàng) khi giao nhận</p>
    <p class="auto-style31" style="box-sizing: border-box; margin: 0px 0px 15px; color: rgb(37, 37, 37); font-family: &quot;Product Sans&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <span style="box-sizing: border-box; font-size: 20px;"><span style="box-sizing: border-box; background: white;"><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;, serif;"><span style="box-sizing: border-box; font-family: Calibri, sans-serif;"><span style="box-sizing: border-box; color: black;">Trường hợp sản phẩm bị lỗi, hư hỏng, trầy xước, không đúng số lượng, chất lượng... quý khách vui lòng quay lại kiện hàng trước khi mở ra và liên hệ với nhân viên bán hàng của&nbsp;<b style="box-sizing: border-box; font-weight: 700;">Cleverbox</b>&nbsp;để được hỗ&nbsp;trợ thông qua Hotline: 0896918585</span></span></span></span></span></p>
    <p class="auto-style9" style="box-sizing: border-box; margin: 0px 0px 11px; color: rgb(37, 37, 37); font-family: &quot;Product Sans&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <span style="box-sizing: border-box; font-size: 20px;"><span style="box-sizing: border-box; line-height: 21.4px;"><span style="box-sizing: border-box; font-family: Calibri, sans-serif;">Sau khi gửi Yêu cầu Trả hàng/Hoàn tiền hoặc Khiếu nại vận chuyển, vui lòng bảo quản và giữ nguyên trạng bưu kiện và sản phẩm</span></span></span></p>
    <p class="auto-style9" style="box-sizing: border-box; margin: 0px 0px 11px; color: rgb(37, 37, 37); font-family: &quot;Product Sans&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <span style="box-sizing: border-box; font-size: 20px;"><span style="box-sizing: border-box; line-height: 21.4px;"><span style="box-sizing: border-box; font-family: Calibri, sans-serif;">Khi có khiếu nại xảy ra, khách hàng có trách nhiệm hỗ trợ Cleverbox trong quá trình xác minh thông tin bằng cách cung cấp thông tin trung thực, chính xác khi shop liên hệ</span></span></span></p>
    <p class="auto-style9" style="box-sizing: border-box; margin: 0px 0px 15px; color: rgb(37, 37, 37); font-family: &quot;Product Sans&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <span style="box-sizing: border-box; font-size: 20px;"><span style="box-sizing: border-box; background: white;"><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;, serif;"><strong style="box-sizing: border-box; font-weight: 700;"><span style="box-sizing: border-box; font-family: Calibri, sans-serif;"><span style="box-sizing: border-box; color: black;">Hủy đơn hàng</span></span></strong></span></span></span></p>
    <p class="auto-style9" style="box-sizing: border-box; margin: 0px 0px 15px; color: rgb(37, 37, 37); font-family: &quot;Product Sans&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <span style="box-sizing: border-box; font-size: 20px;"><span style="box-sizing: border-box; background: white;"><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;, serif;"><span style="box-sizing: border-box; font-family: Calibri, sans-serif;"><span style="box-sizing: border-box; color: black;">Đơn hàng sẽ bị hủy sau<span>&nbsp;</span><b style="box-sizing: border-box; font-weight: 700;">03</b><span>&nbsp;</span>lần nhân viên giao nhận không thể liên lạc hoặc không thể giao hàng được cho Quý khách.</span></span></span></span></span></p>
    <p class="auto-style9" style="box-sizing: border-box; margin: 0px 0px 15px; color: rgb(37, 37, 37); font-family: &quot;Product Sans&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <span style="box-sizing: border-box; font-size: 20px;"><span style="box-sizing: border-box; background: white;"><span style="box-sizing: border-box; font-family: &quot;Times New Roman&quot;, serif;"><span style="box-sizing: border-box; font-family: Calibri, sans-serif;"><span style="box-sizing: border-box; color: black;">Quý Khách hàng vui lòng liên hệ đường dây chăm sóc khách hàng&nbsp;tại Hotline: 0896918585 để được hướng dẫn và chăm sóc.</span></span></span></span></span></p>
</div>
<p>
    &nbsp;</p>
</asp:Content>
